### ISSUE TITLE
Reset BMS after replacing battery

### ISSUE THREAD

**Issue by smarteditor-io** [gregyedlik/handshake#3]
We rebuild these Bosch bike batteries.

What have you uncovered why the BMS becomes inoperable after being de-powered (battery removed).

The way we have been managing this is to connect power to the BMS separate to the battery before it is disconnected and keeping the bms powered during the repair process.

Have you uncovered enough to make a device to reset the bms after it loses power?

**Comment by gregyedlik** [comment]
I replaced hundreds of first and second generation Bosch BMSs, they do not become inoperable upon disconnect. We used to store the removed BMSs in a box for weeks and month, and they would start right up when attached to a new battery. (Shimano BMSs do lock themselves when disconnected!)
